title: SSUloger
email: qdwns9704@gmail.com
description: 숭실대학교 오픈소스기반 기초설계 프로젝트
baseurl: ""
url: http://qdwns9704.github.io
github_username: jekyll
timezone: Asia/Seoul

# Build settings
theme: minima
plugins:
  - jekyll-feed

